---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: "master01"
  ip: "10.10.14.3"
  memory: 8192
  cpus: 2
  roles:
    - kube-master
    - etcd
- name: "master02"
  ip: "10.10.14.4"
  memory: 8192
  cpus: 2
  roles:
    - kube-master
    - etcd
- name: "master03"
  ip: "10.10.14.5"
  memory: 8192
  cpus: 2
  roles:
    - kube-master
    - etcd
- name: "minion01"
  ip: "10.10.14.6"
  memory: 32768
  cpus: 16
  volumes:
    - name: sda
      size: 50
      mount: /var/lib/docker/
  roles:
    - kube-node
- name: "minion02"
  ip: "10.10.14.7"
  memory: 8192
  cpus: 4
  roles:
    - kube-node
